name: Update Favicon from Avatar

on:
  schedule:
    - cron: '0 */12 * * *'  # every 12 hours
  workflow_dispatch:        # allow manual run too

jobs:
  update-favicon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests Pillow

      - name: Check and update avatar
        run: python scripts/check_avatar.py

      - name: Commit and push if favicon changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add app/favicon.ico .avatar_hash
            git commit -m "Update favicon from new GitHub avatar"
            git push
          else
            echo "No changes to commit."
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
