name: Update Favicon

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  update-favicon:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests Pillow

      - name: Check and update avatar
        run: python scripts/check_avatar.py

      - name: Commit and push if favicon changed
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          if [[ `git status --porcelain` ]]; then
            git add app/favicon.ico public/images/avatar.png .avatar_hash
            git commit -m "Update favicon and header image from GitHub avatar"
            git push
          else
            echo "No changes to commit."
          fi
