name: Update Screenshots

on:
  workflow_dispatch:
  # This will cause infinite loops, commenting out for now.
  # deployment_status:
  #   types: [success]

jobs:
  update-screenshots:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get deployment URL from GitHub API
        id: get_url
        run: |
          REPO_INFO=$(curl -s https://api.github.com/repos/$GITHUB_REPOSITORY)
          DEPLOYMENT_URL=$(echo $REPO_INFO | jq -r .homepage)
          echo "Deployment URL: $DEPLOYMENT_URL"
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV

      - name: Run screenshot script
        run: |
          node scripts/take_screenshots.js $DEPLOYMENT_URL

      - name: Commit and push updated screenshots
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b screenshots
          git add screenshot-light.png screenshot-dark.png
          git commit -m "Update automated screenshots"
          git push origin screenshots
